CREATE DATABASE TURISMO
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8utf8_general_ci;

USE TURISMO;

CREATE TABLE CONTINENTES (
	ID_CONTINENTE SMALLINT(3) AUTO_INCREMENT NOT NULL,
    NOME_CONTINENTE VARCHAR(20) NOT NULL,
    AREA_CONTINENTE VARCHAR(15) NOT NULL,
    PRIMARY KEY(ID_CONTINENTE)
) DEFAULT CHARSET utf8;

CREATE TABLE PAISES (
	ID_PAIS SMALLINT(3) AUTO_INCREMENT NOT NULL,
    NOME_PAIS VARCHAR(30) NOT NULL,
    CAPITAL_PAIS VARCHAR(30) NOT NULL,
    LINGUA_PAIS VARCHAR(12) NOT NULL,
    MOEDA_PAIS TEXT NOT NULL,
    PRESIDENTE_PAIS VARCHAR(20) NOT NULL,
    AREA_PAIS VARCHAR(15) NOT NULL,
    REGIME_PAIS TEXT NOT NULL,
    DATA_INDEPENTECIA DATE NOT NULL,
    PRIMARY KEY(ID_PAIS)
) DEFAULT CHARSET utf8 ;

CREATE TABLE CIDADE (
	ID_CIDADE SMALLINT(3) AUTO_INCREMENT NOT NULL,
    NOME_CIDADE VARCHAR(20) NOT NULL,
    POPULACAO_CIDADE INT(11) NOT NULL,
    DATA_FUNDACAO_CIDADE DATE NOT NULL,
    PRIMARY KEY(ID_CIDADE)
) DEFAULT CHARSET utf8;

CREATE TABLE HOTEL (
	ID_HOTEL SMALLINT(3) AUTO_INCREMENT NOT NULL,
    NOME_HOTEL VARCHAR(20) NOT NULL,
    TIPO_HOTEL VARCHAR(9),
    PRECO_DIARIA FLOAT(6,2),
    PRIMARY KEY(ID_HOTEL)
) DEFAULT CHARSET utf8;

ALTER TABLE PAISES
ADD column CONTINENTE_PAIS SMALLINT(3) NOT NULL AFTER ID_PAIS;

ALTER TABLE PAISES
ADD FOREIGN KEY (CONTINENTE_PAIS)
REFERENCES CONTINENTES(ID_CONTINENTE);

ALTER TABLE CIDADE
ADD COLUMN PAIS_CIDADE SMALLINT(3) NOT NULL AFTER ID_CIDADE;

ALTER TABLE CIDADE
ADD FOREIGN KEY (PAIS_CIDADE)
REFERENCES PAISES(ID_PAIS);

ALTER TABLE HOTEL
ADD column CIDADE_HOTEL smallint(3) NOT NULL AFTER ID_HOTEL;

ALTER TABLE HOTEL
ADD FOREIGN KEY (CIDADE_HOTEL)
REFERENCES CIDADE(ID_CIDADE);

INSERT INTO CONTINENTES VALUES
(default, 'AMÉRICA',  '42.549.000'),
(default, 'ÁFRICA', '922.011.000', '30.370.000'),
(default, 'ÁSIA', '43.810.000'),
(default, 'EUROPA', '10.180.000'),
(default, 'OCEANIA', '7.600.000');

SELECT * FROM CONTINENTES;

ALTER TABLE PAISES
modify COLUMN MOEDA_PAIS text;

DESC PAISES;

SELECT * FROM PAISES;

INSERT INTO PAISES VALUES
(default, 1, 'BRASIL', 'BRASILIA', 'PORTUGUÊS', 'REAL', 'JAIR BOLSONARO', '208.494.900', '8.515.767,049', 'REPÚBLICA PRESIDENCIALISTA', '1822-09-07'),
(DEFAULT, 1, 'EUA', 'WASHINGTON', 'INGLÊS', 'DÓLAR', 'DONALD TRUMP', '325.719.178', '9.371.175', 'REPÚBLICA PRESIDENCIALISTA', '1776-07-04'),
(DEFAULT, 1, 'CANADÁ', 'OTAWA', 'INGLÊS E FRANCÊS', 'DÓLAR CANADENSE', 'JUSTII TRUDEAU', '37.242.571', '9.984.670', 'Democracia parlamentar
e Monarquia constitucional federal', '1867-07-01'),
(DEFAULT, 1, 'MÉXICO', 'CIDADE DO MÉXICO', 'ESPANHOL E 67 LÍNGUAS, NENHUMA OFICIAL', 'PESO MEXICANO', 'ANDRÉS OBRADOR', '123.675.325', '1.958.201', 'República presidencialista', '1810-07-16'),
(DEFAULT, 1, 'ARGENTINA', 'BUENOS AIRES', 'ESPANHOL', 'PESO ARGENTINO', 'MAURICIO MACRI', '43.590.368', '2.780.400', 'REPÚBLICA PRESIDENCIALISTA', '1816-07-09');

INTO PAISES VALUES
(default, 2, 'ÁFRICA DO SUL', 'PETRÓRIA', 'ÁFRICANS/INGLÊS', 'RAND', 'CYRIL RAMAPHOSA', '1.221.037', 'República parlamentarista unitária de partido dominante', '1910-05-31'),
(default, 2, 'ANGOLA', 'LUANDA', 'PORTUGÊS', 'KWANZA', 'JOÃO LOURENÇO', '1.246.700', 'REPÚBLICA PRESIDENCIALISTA', '1975-11-11'),
(default, 2, 'CAMARÕES', 'YAOUNDÉ', 'FRANCÊS/INGLÊS', 'FRANCO CFA CENTRAL', 'PAUL BIYA', '475.442', 'REPÚBLICA PARLAMENTARISTA', '1960-01-01'),
(default, 2, 'COSTA DO MÁRFIM', 'ABIDJAN', 'FRANCÊS', 'FRANCO CFA OCIDENTAL', 'ALASSANE OUATTARA', '322.463', 'REPÚBLICA PRESIDENCIALISTA', '1960-08-07'),
(default, 2, 'MADAGÁSCAR', 'ANTANANARIVO', 'MALGAXE/FRANCÊS', 'ARIARY', 'ANDRY RAJOELINA', '587.041', 'REPÚBLICA SEMI PRESIDENCIALISTA', '1960-07-26');

INSERT INTO PAISES VALUES
(default, 3, '', '', '', '', '', '', '', '', ''),
(default, 3, '', '', '', '', '', '', '', '', ''),
(default, 3, '', '', '', '', '', '', '', '', ''),
(default, 3, '', '', '', '', '', '', '', '', ''),
(default, 3, '', '', '', '', '', '', '', '', '');


INSERT INTO PAISES VALUES
(default, 3, 'ISRAEL', 'JERUSALÉM', 'HEBRÁICO ÁRABE', 'NOVO SHEKEL', 'REUVEN RIVLIN', '20.772', 'DEMOCRACIA PARLAMENTAR', '1948-05-14'),
(default, 3, 'CHINA', 'BENJIN', 'MANDARIM', 'YUAN', 'XI JIPING', '9.596.961', 'REPUBLICA SOCIALISTA UNIPARTIDÁRIA', '1912-01-01'),
(default, 3, 'JAPÃO', 'TÓQUIO', 'JAPONÊS', 'YEN', 'SHINSÕ ABE', '377.873', 'MONARQUIA CONSTITUCIONAL UNITÁRIA', '0660-02-11'),
(default, 3, 'MONGÓLIA', 'ULAN BATOR', 'MONGOL', 'TUGRIK', 'KHALTMAAGIIN', '1.564.100', 'REPÚBLIVA SEMI PRESIDENCIALISTA', '1921-07-11'),
(default, 3, 'TAILÂNDIA', 'BANGUECOQUE', 'TAILANDÊS', 'BAHT TAILÂNDÊS', 'PRAYUTH CHAN-OCHA', '513.120,15', 'MONARQUIA CONSTITUCIONAL', '1932-06-24');


INSERT INTO PAISES VALUES
(default, 4, 'PORTUGAL', 'LISBOA', 'PORTUGUÊS', 'EURO', 'MARCELO DE SOUZA', '92.256', 'REPÚBLICA SEMIPRESIDENCIALISTA', '0868-01-01'),
(default, 4, 'ALEMANHA', 'BERLIM', 'ALEMÃO', 'EURO', 'ANGELA MERKEL', '357.051', 'REPUBLICA PARLAMENTARISTA', '0962-02-02'),
(default, 4, 'FRANÇA', 'PARIS', 'FRANCÊS', 'EURO', 'EMMANOEL MAKRON', '543.965', 'REPÚBLICA SEMIPRESIDENCIALISTA', '0843-01-01'),
(default, 4, 'INGLATERRA', 'LONDRES', 'INGLÊS', 'LIBRA', 'THERESA MAY', '130.395', 'MONARQUIA PARLAMENTARISTA', '0927-05-13'),
(default, 4, 'ESPANHA', 'MADRID', 'ESPANHOL', 'EURO', 'PEDRO SÁNCHES', '504.030', 'MONARQUIA CONSTITUCIONAL', '1469-01-01');

INSERT INTO PAISES VALUES
(default, 5, 'AUSTRÁLIA', 'CAMBERRA', 'INGLÊS', 'DÓLAR AUSTRALIA', 'ROBERT FRENCH', '7.692.024', 'MONARQUIA PARLAMENTARISTA', '1901-01-01'),
(default, 5, 'NOVA ZELÂDIA', 'WELLINGTON', 'INGLÊS/MAORI', 'DÓLAR NZ', 'JACINDA ARDERN', '268.680', 'MONARQUIA PARLAMENTARISTA', '1907-09-26'),
(default, 5, 'SAMOA', 'APIA', 'INGLÊS/SAMOANO', 'TALA', 'MALIELEGAOI', '2.831', 'REPUBLICA PALRAMENTAR UNIPARTIDARIO', '1962-10-01'),
(default, 5, 'TUVALU', 'FUNAFUTI', 'INGLÊS TUVALUANO', 'DOLAR TUVALU', 'ENELE SAPOAGA', '26', 'MONARQUIA CONSTITUCIONAL', '1978-10-01'),
(default, 5, 'MICRONÉSIA', 'PALIKIR', 'INGLÊS', 'DÓLAR', 'PETER CRISTIAN', '702', 'REPÚBLICA PRESIDENCIALISTA', '1947-07-18');

INSERT INTO `TURISMO`.`PAISES` (`CONTINENTE_PAIS`, `NOME_PAIS`, `CAPITAL_PAIS`, `LINGUA_PAIS`, `MOEDA_PAIS`, `PRESIDENTE_PAIS`, `AREA_PAIS`, `REGIME_PAIS`, `DATA_INDEPENTECIA`) VALUES ('4', 'FINLÂDIA', 'HELSINQUE', 'FINLADÊS/SUECO', 'EURO', 'SAULI NIINISTÖ', '338145', 'REPÚBLICA PARLAMENTARISTA', '1918-01-04');
UPDATE `TURISMO`.`PAISES` SET `AREA_PAIS`='702' WHERE `ID_PAIS`='35';
UPDATE `TURISMO`.`PAISES` SET `AREA_PAIS`='26' WHERE `ID_PAIS`='34';

INSERT INTO CIDADE
(ID_CIDADE, PAIS_CIDADE, NOME_CIDADE, DATA_FUNDACAO_CIDADE, POPULACAO_CIDADE)
VALUES
(DEFAULT, '', '', '', ''),
(DEFAULT, '', '', '', ''),
(DEFAULT, '', '', '', '');

INSERT INTO CIDADE
(ID_CIDADE, PAIS_CIDADE, NOME_CIDADE, DATA_FUNDACAO_CIDADE, POPULACAO_CIDADE)
VALUES
 VALUES
(default, '1', 'SÃO LUÍS', '1612-07-08', '100'),
(DEFAULT, '1', 'SÃO PAULO', '1554-01-25', '100'),
(DEFAULT, '1', 'RIO DE JANEIRO', '1565-03-01', '900');

INSERT INTO CIDADE VALUES
(DEFAULT, '2', 'NOVA YORK', '1625-05-13', '788'),
(DEFAULT, '2', 'CHICAGO', '1632-03-22', '737'),
(default, '2', 'BOSTON', '1701-06-06', '698');


INSERT INTO CIDADE VALUES
(DEFAULT, '2', 'NOVA YORK', '1625-05-13', '788'),
(DEFAULT, '2', 'CHICAGO', '1632-03-22', '737'),
(default, '2', 'BOSTON', '1701-06-06', '698');

INSERT INTO HOTEL
(ID_HOTEL, CIDADE_HOTEL, NOME_HOTEL, TIPO_HOTEL, PRECO_DIARIA)
VALUES
(DEFAULT, '', '', '', ''),
(DEFAULT, '', '', '', ''),
(DEFAULT, '', '', '', ''),
(DEFAULT, '', '', '', '');
