CREATE database IF not exists CURRICULUM
DEFAULT CHARACTER SET utf8
default collate utf8_general_ci;

DESC USUARIO;

CREATE TABLE USUARIO(
	ID_USUARIO INT(5) auto_increment NOT NULL,
    NOME_USUARIO VARCHAR(50) NOT NULL,
    CPF INT(11) NOT NULL,
    DATA_NASCIMENTO DATE,
    SEXO ENUM('M', 'F') NOT NULL,
    NACIONALIDADE VARCHAR(20) NOT null DEFAULT 'BRASIL',
    primary key(ID_USUARIO)
) DEFAULT charset = utf8;

ALTER TABLE USUARIO
ADD COLUMN OBJETIVO TEXT;

ALTER TABLE USUARIO
MODIFY COLUMN DATA_NASCIMENTO DATE NOT NULL;

CREATE TABLE IF NOT EXISTS ENDERECO(
	ID_ENDERECO INT(5) auto_increment NOT NULL,
    END_RUA varchar (30) NOT NULL,
    END_NUMERO INT(5) NOT NULL,
    END_BAIRRO VARCHAR (30) NOT NULL,
    END_COMPLEMENTO TEXT,
    END_CIDADE VARCHAR (30) NOT NULL,
    END_ESTADO VARCHAR (30) NOT NULL,
    END_PAIS VARCHAR (30) NOT NULL DEFAULT 'BRASIL',
    PRIMARY KEY(ID_ENDERECO)
) DEFAULT CHARSET utf8;


CREATE TABLE IF NOT EXISTS CONTATO (
	ID_CONTATO INT(4) AUTO_INCREMENT NOT NULL,
    ID_EMAIL VARCHAR(40) NOT NULL,
    ID_TELEFONE1 VARCHAR(11),
    ID_TELEFONE2 VARCHAR(11),
    PRIMARY KEY(ID_CONTATO)
) DEFAULT CHARSET utf8;

CREATE TABLE IF NOT EXISTS FORMACAO(
	ID_FORMACAO INT(4) AUTO_INCREMENT NOT NULL,
    FOR_ESCOLARIDADE ENUM('ENSINO MÉDIO', 'TÉCNICO', 'GRADUAÇÃO', 'PÓS-GRADUAÇÃO', 'DOTOURADO'),
    FOR_ESTADO ENUM('CURSANDO', 'CONCLUÍDO'),
    FOR_ANO_CONCLUSAO INT(4),
    PRIMARY KEY(ID_FORMACAO)
) DEFAULT CHARSET utf8;

CREATE TABLE IF NOT EXISTS PROFISSAO(
	ID_PROFICAO INT(4) auto_increment NOT NULL,
    PROF_EMPRESA VARCHAR (30) NOT NULL,
    PROF_CARGO VARCHAR(20) NOT NULL,
    PROF_PERIODO_INICIO DATE,
    PROF_PERIODO_FINAL DATE,
	PROF_DESCRICAO TEXT,
	primary key(ID_PROFICAO)
) DEFAULT CHARSET utf8;
